language: php

php:
  - 7.2

install:
  - composer install

script:
  - composer lint
  - composer test

after_script:
  - composer coveralls

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
